//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okoone_Assignment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class User
    {
        [Required(ErrorMessage = "Please Input Username", AllowEmptyStrings = false)]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please Input Password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Must be 8 char long")]
        public string Password { get; set; }
        [Compare("Password", ErrorMessage = "Password not match")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string ComfirmPassword { get; set; }
        [Required(ErrorMessage = "Please Input Name", AllowEmptyStrings = false)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Input Name", AllowEmptyStrings = false)]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please Input Email", AllowEmptyStrings = false)]
        public string Email { get; set; }
    }
    public partial class UserLogin {

        [Required(ErrorMessage = "Please Input Username", AllowEmptyStrings = false)]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please Input Password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        
        public string LastName { get; set; }
        
    
    }
}
